--

### Deploy เป็น Web App

1. กด **Deploy** → **New Deployment**
2. เลือก Type = **Web App**
3. Execute as = **Me**
4. Who has access = **Anyone**
5. กด **Deploy**
6. **คัดลอก URL** ที่ได้ไว้ครับ จะได้ใช้ใน App.jsx

---

URL จะหน้าตาแบบนี้ครับ
```
https://script.google.com/macros/s/XXXXXXXXXX/exec
https://script.google.com/macros/s/AKfycbytwotuAasn9-ikmI7WOodPmQBXppN9AFAScdGZnJ0M_mNrBFnqFsxTKIpn5TCn4SRK/exec
https://script.google.com/macros/s/AKfycbytwotuAasn9-ikmI7WOodPmQBXppN9AFAScdGZnJ0M_mNrBFnqFsxTKIpn5TCn4SRK/exec
https://script.google.com/macros/s/AKfycbytwotuAasn9-ikmI7WOodPmQBXppN9AFAScdGZnJ0M_mNrBFnqFsxTKIpn5TCn4SRK/exec



AKfycbytwotuAasn9-ikmI7WOodPmQBXppN9AFAScdGZnJ0M_mNrBFnqFsxTKIpn5TCn4SRK

Admin Line User ID
U436fe84072a2d1584a0a9a884ad92d10
U436fe84072a2d1584a0a9a884ad92d10

Channel access token (long-lived)
4CZOG8H3cwgOKiv7LGLgJ9rtTi+qux/MuudliS0vh5/VTL/SKL/NpeyC1Rs9zUiZ1YkTwfO/DkaKYY/Brsh8KynQY6vsVfPXD0cYpKlWPqf/J0ZQubHHyCBLPUI/TFzbkmWtnqkaDxp9jFgP/lB7hwdB04t89/1O/w1cDnyilFU=

PYKQP0Umjj3IjaWZWx6cOvYiqXtY702mJC7VHibqxL+IdcFl8Ma2AJ0YEUlhE7gP1YkTwfO/DkaKYY/Brsh8KynQY6vsVfPXD0cYpKlWPqe0hEmh8aKk7IdZHIB7tdV2BKwqtjqYWgL91sFU/4/wqQdB04t89/1O/w1cDnyilFU=